# Generated by Django 4.1.7 on 2023-03-12 18:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("service_parsing_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="count_solved",
            field=models.IntegerField(default=None, null=True, verbose_name="Count Solved"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="difficulty",
            field=models.IntegerField(default=None, null=True, verbose_name="Difficulty"),
        ),
    ]
